### ISSUE TITLE
Will there be wiring instructions in the future?

### ISSUE THREAD

**Issue by cmoo2011** [jasoneppink/Tennis-for-Two#1]
This really looks like a interesting project. Thank you for making it open source.

I recently got a retired CRT oscilloscope from my Univ.'s physic lab, would be super cool if there is a chance to play the first ever video game on it.

Is it possible that there will be updates on wiring? Or any other hint would also be deeply appreciated.

Best regards

**Comment by jasoneppink** [comment]
Thanks for your interest! Unfortunately I left the Museum before I had a chance to document the wiring. (I'll update the readme file to reflect that reality now.) Instead, I'll point you to the Evil Mad Scientist project my project was based on: https://www.evilmadscientist.com/2008/resurrecting-tennis-for-two-a-video-game-from-1958/
